#pragma once

#ifndef DECLARE_FUNCTION_PTR
#define DECLARE_FUNCTION_PTR(RETURN_TYPE, CALLING_CONVENTION, FUNCTION_NAME, ADDRESS, ...)
#endif

#ifndef DECLARE_LIB_FUNCTION_PTR
#define DECLARE_LIB_FUNCTION_PTR(RETURN_TYPE, LIBRARY_NAME, FUNCTION_NAME, ...)
#endif

#ifndef DECLARE_HOOK
#define DECLARE_HOOK(RETURN_TYPE, CALLING_CONVENTION, FUNCTION_NAME, ADDRESS, ...)
#endif

#ifndef DECLARE_VTABLE_HOOK
#define DECLARE_VTABLE_HOOK(RETURN_TYPE, CALLING_CONVENTION, CLASS_NAME, FUNCTION_NAME, ...)
#endif

#ifndef DECLARE_ASM_HOOK_32
#define DECLARE_ASM_HOOK_32(NAME, ADDRESS)
#endif

#ifndef DECLARE_ASM_HOOK_64
#define DECLARE_ASM_HOOK_64(NAME, ADDRESS)
#endif

#ifndef INSTALL_HOOK
#define INSTALL_HOOK(FUNCTION_NAME)
#endif

#ifndef INSTALL_HOOK_EXPLICIT
#define INSTALL_HOOK_EXPLICIT(FUNCTION_NAME, ADDRESS)
#endif

#ifndef INSTALL_VTABLE_HOOK
#define INSTALL_VTABLE_HOOK(CLASS_NAME, OBJECT, FUNCTION_NAME, FUNCTION_INDEX)
#endif

#ifndef INSTALL_ASM_HOOK_32
#define INSTALL_ASM_HOOK_32(NAME)
#endif

#ifndef INSTALL_ASM_HOOK_32_EXPLICIT
#define INSTALL_ASM_HOOK_32_EXPLICIT(NAME, ADDRESS)
#endif

#ifndef INSTALL_ASM_HOOK_64
#define INSTALL_ASM_HOOK_64(NAME)
#endif

#ifndef INSTALL_ASM_HOOK_64_EXPLICIT
#define INSTALL_ASM_HOOK_64_EXPLICIT(NAME, ADDRESS)
#endif
