#pragma once

enum ESonicState : int32_t
{
    ESonicState_Default = -1,
    ESonicState_StateAcceleCombo1 = 146,           // StateAttackRoot
    ESonicState_StateAcceleCombo2 = 147,           // StateAttackRoot
    ESonicState_StateAquaBallJump = 119,
    ESonicState_StateAquaBallStand = 118,
    ESonicState_StateAquaBallStomping = 120,
    ESonicState_StateAttackRoot = 131,
    ESonicState_StateAuraTrain = 188,
    ESonicState_StateAvoid = 137,
    ESonicState_StateAvoidLocal = 140,
    ESonicState_StateAvoidToTarget = 139,
    ESonicState_StateAvoidUpper = 138,
    ESonicState_StateAwakening = 26,
    ESonicState_StateBallMove = 169,
    ESonicState_StateBaseJump = 101,
    ESonicState_StateBatterBox = 200,
    ESonicState_StateBattleStart = 155,
    ESonicState_StateBoarding = 180,
    ESonicState_StateBossCounter = 156,
    ESonicState_StateBrake = 6,
    ESonicState_StateBrakeNeutral = 7,
    ESonicState_StateBreathe = 43,
    ESonicState_StateBumpJump = 16,
    ESonicState_StateCaught = 164,
    ESonicState_StateChargeAttack = 148,           // StateAttackRoot
    ESonicState_StateClimbing = 99,                // StateWallActionRoot
    ESonicState_StateClimbingEdge = 98,            // StateWallActionRoot
    ESonicState_StateCloudJump = 189,
    ESonicState_StateHomingFinish = 133,           // StateAttackRoot
    ESonicState_StateComboMove = 128,
    ESonicState_StateComboStep = 129,
    ESonicState_StateComboWarp = 130,
    ESonicState_StateCrasher = 150,                // StateAttackRoot
    ESonicState_StateCrossSlash = 152,             // StateAttackRoot
    ESonicState_StateDamage = 28,                  // StateDamageRoot
    ESonicState_StateDamageBlowOff = 30,           // StateDamageRoot
    ESonicState_StateDamageBlowOffHeavy = 31,      // StateDamageRoot
    ESonicState_StateDamageLava = 37,
    ESonicState_StateDamageQuake = 32,             // StateDamageRoot
    ESonicState_StateDamageRoot = 27,
    ESonicState_StateDamageRunning = 33,           // StateDamageRoot
    ESonicState_StateDamageTurnBack = 29,          // StateDamageRoot
    ESonicState_StateDead = 38,
    ESonicState_StateDebuff = 177,
    ESonicState_StateDestination = 185,
    ESonicState_StateDiving = 78,                  // StateDivingRoot
    ESonicState_StateDivingDamage = 80,            // StateDivingRoot
    ESonicState_StateDivingFall = 79,              // StateDivingRoot
    ESonicState_StateDivingRoot = 77,
    ESonicState_StateDivingSpecial = 83,           // StateDivingSpecialRoot
    ESonicState_StateDivingSpecialDamage = 86,     // StateDivingSpecialRoot
    ESonicState_StateDivingSpecialDashRing = 84,   // StateDivingSpecialRoot
    ESonicState_StateDivingSpecialFall = 85,       // StateDivingSpecialRoot
    ESonicState_StateDivingSpecialPush = 87,       // StateDivingSpecialRoot
    ESonicState_StateDivingSpecialRoot = 82,
    ESonicState_StateDivingSpring = 81,            // StateDivingRoot
    ESonicState_StateDrift = 109,
    ESonicState_StateDriftDash = 110,
    ESonicState_StateDriftAir = 111,
    ESonicState_StateDropDash = 112,
    ESonicState_StateFall = 15,
    ESonicState_StateFallWithKodama = 195,
    ESonicState_StateFallWithCannonball = 198,
    ESonicState_StateFallFlip = 22,
    ESonicState_StateFallingDead = 39,
    ESonicState_StateFallSlope = 21,
    ESonicState_StateFan = 168,
    ESonicState_StateFixedGoal = 126,
    ESonicState_StateFloat = 107,
    ESonicState_StateFly = 102,
    ESonicState_StateFlyLocal = 105,
    ESonicState_StateFlyLocal2D = 106,
    ESonicState_StateFlyOnPath = 104,
    ESonicState_StateFlyTurn = 103,
    ESonicState_StateGoal = 124,
    ESonicState_StateGoal2 = 125,
    ESonicState_StateGrind = 46,                   // StateGrindRoot
    ESonicState_StateGrindDamage = 49,             // StateGrindRoot
    ESonicState_StateGrindDamageAir = 50,          // StateGrindRoot
    ESonicState_StateGrindJump = 47,               // StateGrindRoot
    ESonicState_StateGrindDoubleJump = 48,         // StateGrindRoot
    ESonicState_StateGrindRoot = 45,
    ESonicState_StateGrindStep = 51,
    ESonicState_StateGuard = 145,
    ESonicState_StateGuardedFlipBack = 34,         // StateDamageRoot
    ESonicState_StateHangPole = 170,
    ESonicState_StateHangPoleJump = 171,
    ESonicState_StateHoldStand = 159,
    ESonicState_StateHomingAttack = 62,            // StateAttackRoot
    ESonicState_StateHomingAttackRoot = 61,        // StateAttackRoot
    ESonicState_StateHomingAttackInStorm = 63,     // StateAttackRoot
    ESonicState_StateHomingFinished = 64,          // StateAttackRoot
    ESonicState_StateHomingRepelled = 65,
    ESonicState_StateHomingShot = 153,             // StateAttackRoot
    ESonicState_StateImpactGimmick = 182,
    ESonicState_StateJump = 8,
    ESonicState_StateJumpWithKodama = 194,
    ESonicState_StateJumpBoardLaunch = 167,
    ESonicState_StateBounceJump = 11,
    ESonicState_StateRecoveryJump = 12,
    ESonicState_StateSpringJump = 162,
    ESonicState_StateSpringJumpHeadLand = 163,
    ESonicState_StateKickBox = 173,
    ESonicState_StateLavaDead = 44,
    ESonicState_StateLeftStep = 71,
    ESonicState_StateLeftStepRun = 73,
    ESonicState_PlayerStateLevitation = 211,
    ESonicState_StateLightDash = 25,
    ESonicState_StateLoopKick = 149,               // StateAttackRoot
    ESonicState_StateMoveInWarningArea = 186,
    ESonicState_StateMoveToBatterBox = 201,
    ESonicState_StateMoveToBossArea = 187,
    ESonicState_StateMoveToReflexesPanel = 203,
    ESonicState_StateNoisyGoal = 127,
    ESonicState_StateOperateConsole = 181,
    ESonicState_StateParalysis = 36,
    ESonicState_StateParriedFlipBack = 35,
    ESonicState_StateParry = 141,
    ESonicState_StateParryStand = 142,             // StateParry
    ESonicState_StatePipeMove = 165,
    ESonicState_StatePipeOut = 166,
    ESonicState_StatePressDead = 42,
    ESonicState_StatePursuitKick = 132,            // StateAttackRoot
    ESonicState_StatePushBox = 172,
    ESonicState_StateQuickCyloop = 134,            // StateAttackRoot
    ESonicState_StateQuickStep = 67,               // StateQuickStepRoot
    ESonicState_StateQuickStepCrash = 70,          // StateQuickStepRoot
    ESonicState_StateQuickStepJump = 75,
    ESonicState_StateQuickStepDoubleJump = 76,
    ESonicState_StateQuickStepLeft = 68,           // StateQuickStepRoot
    ESonicState_StateQuickStepRight = 69,          // StateQuickStepRoot
    ESonicState_StateQuickStepRoot = 66,
    ESonicState_StateRecoil = 20,
    ESonicState_StateRecovery = 161,
    ESonicState_StateReflexesPanel = 202,
    ESonicState_StateReflexesPanelLeftStep = 204,
    ESonicState_StateReflexesPanelRightStep = 205,
    ESonicState_StateRightStep = 72,
    ESonicState_StateRightStepRun = 74,
    ESonicState_StateRun = 4,
    ESonicState_StateRunWithKodama = 193,
    ESonicState_StateRunWithCannonball = 196,
    ESonicState_StateRunawayBee = 191,
    ESonicState_StateRunningStart = 123,
    ESonicState_StateSandSki = 174,
    ESonicState_StateSandSkiBlow = 175,
    ESonicState_StateSendSignal = 183,
    ESonicState_StateSleep = 0,
    ESonicState_StateSliding = 59,                 // StateSquatRoot
    ESonicState_StateSlidingToStand = 60,
    ESonicState_StateSlingshot = 176,
    ESonicState_StateSmash = 135,                  // StateAttackRoot
    ESonicState_StateSmashSS = 136,                // StateAttackRoot
    ESonicState_StateSonicBoomKick = 151,          // StateAttackRoot
    ESonicState_StateSpin = 113,
    ESonicState_StateSpinAttack = 14,
    ESonicState_StateSpinBoost = 116,
    ESonicState_StateSpinBoostCharge = 115,
    ESonicState_StateSpinMove = 117,
    ESonicState_StateSpinDash = 114,               // StateAttackRoot
    ESonicState_StateSpinSlash = 154,              // StateAttackRoot
    ESonicState_StateSquat = 19,                   // StateSquatRoot
    ESonicState_StateSquatRoot = 18,
    ESonicState_StateStandRoot = 1,
    ESonicState_StateStandWithKodama = 192,
    ESonicState_StateStand = 2,                    // StateStandRoot
    ESonicState_StateStandWithCannonball = 197,
    ESonicState_StateStolenEmerald = 179,
    ESonicState_StateStorm = 178,
    ESonicState_StateSuffocatingDead = 41,
    ESonicState_StateTakeBehind = 143,
    ESonicState_StateTakeBehindSS = 144,
    ESonicState_StateTalkMode = 160,
    ESonicState_StateThrowCannonball = 199,
    ESonicState_StateTreadmill = 190,
    ESonicState_StateTreeJump = 243,
    ESonicState_StateTumble = 17,
    ESonicState_StateTurn = 5,
    ESonicState_StateUpDead = 40,
    ESonicState_StateUpDownPole = 121,
    ESonicState_StateUpDownPoleDamage = 122,
    ESonicState_StateWakeUp = 3,
    ESonicState_StateWarpEnd = 158,
    ESonicState_StateWarpStart = 157,
    ESonicState_StateWaterFall = 184,
    ESonicState_StateAirBoost = 23,
    ESonicState_StateWithAnimalRoot = 206,
    ESonicState_StateFallWithAnimal = 210,         // StateWithAnimalRoot
    ESonicState_StateJumpWithAnimal = 209,         // StateWithAnimalRoot
    ESonicState_StateDoubleJump = 9,
    ESonicState_StateRunWithAnimal = 208,          // StateWithAnimalRoot
    ESonicState_StateStandWithAnimal = 207,        // StateWithAnimalRoot
    ESonicState_StateStomping = 52,                // StateAttackRoot
    ESonicState_StateStompingAttack = 55,          // StateAttackRoot
    ESonicState_StateStompingBounce = 58,          // StateAttackRoot
    ESonicState_StateStompingDown = 54,            // StateAttackRoot
    ESonicState_StateStompingFlip = 53,            // StateAttackRoot
    ESonicState_StateStompingLand = 57,            // StateAttackRoot
    ESonicState_StateStompingPress = 56,           // StateAttackRoot
    ESonicState_StateWallHanging = 90,             // StateWallActionRoot
    ESonicState_StateWallHoming = 92,
    ESonicState_StateWallJump = 96,
    ESonicState_StateWallJumpReady = 97,
    ESonicState_StateWallLanding = 93,             // StateWallActionRoot
    ESonicState_StateWallLeave = 100,
    ESonicState_StateWallReset = 95,               // StateWallActionRoot
    ESonicState_StateWallRest = 91,                // StateWallActionRoot
    ESonicState_StateWallSlideDown = 94,           // StateWallActionRoot
    ESonicState_StateWallActionRoot = 88,
    ESonicState_StateWallMove = 89                 // StateWallActionRoot
};